#!/usr/bin/env bash
# 1-show_attached_IPs: display all active IPv4 addresses without ip/ifconfig

# Read IPv4 addresses from /proc/net/fib_trie
grep -oP '32 host ((\d{1,3}\.){3}\d{1,3})' /proc/net/fib_trie | awk '{print $3}'
